services:
  mysql-productos:
    image: mysql:8.0
    container_name: mysql-productos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: web-dbase
      MYSQL_USER: web
      MYSQL_PASSWORD: web123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: api-productos
    depends_on:
      - mysql-productos
    environment:
      MYSQL_HOST: mysql-productos
      MYSQL_USER: web
      MYSQL_PASSWORD: web123456
      MYSQL_DATABASE: web-dbase
    ports:
      - "8000:8000"

volumes:
  db_data:
