services:
  mysql-productos:
    image: mysql:8.0
    container_name: mysql-productos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: web-dbase
      MYSQL_USER: web
      MYSQL_PASSWORD: web123456

    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123456"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  api:
    build: .
    container_name: api-productos
    restart: always
    depends_on:
      mysql-productos:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql-productos
      MYSQL_USER: web
      MYSQL_PASSWORD: web123456
      MYSQL_DATABASE: web-dbase
    ports:
      - "8000:8000"

volumes:
  db_data:

